BEGIN;
-- ============================================================
-- BDD CORREGIDA Y REVISADA - PostgreSQL
-- Sistema de Registro de Estudiantes de Educación Especial
--XXXX
-- 21 TABLAS
-- Incluye:
--   * PK y FK
--   * relaciones 1:1 y N:M
--   * UNIQUE y CHECK
--   * índices necesarios
--   * triggers para reglas que no conviene expresar con CHECK
--   * corrección de restricciones y datos iniciales
--
-- IMPORTANTE:
-- Ejecutar sobre una BDD vacía o adaptar a una migración si ya existen datos.
-- ============================================================


-- ============================================================
-- 1. ESTUDIANTE
-- ============================================================
CREATE TABLE "Estudiante" (
    "id_estudiante" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "codigo_sie_cee" VARCHAR(50) NOT NULL,
    "apellido_paterno" VARCHAR(100) NOT NULL,
    "apellido_materno" VARCHAR(100),
    "nombre1" VARCHAR(100) NOT NULL,
    "nombre2" VARCHAR(100),
    "pais_nacimiento" VARCHAR(100) NOT NULL,
    "departamento_nacimiento" VARCHAR(100) NOT NULL,
    "provincia_nacimiento" VARCHAR(100) NOT NULL,
    "localidad_nacimiento" VARCHAR(100) NOT NULL,
    "tipo_documento" VARCHAR(50) NOT NULL,
    "numero_documento" VARCHAR(50) NOT NULL,
    "complemento_documento" VARCHAR(20),
    "lugar_expedicion_documento" VARCHAR(100),
    "fecha_nacimiento" DATE NOT NULL,
    "sexo" VARCHAR(30) NOT NULL,
    "tiene_certificado_nacimiento" BOOLEAN NOT NULL DEFAULT FALSE,
    "certificado_oficialia" VARCHAR(100),
    "certificado_libro" VARCHAR(50),
    "certificado_partida" VARCHAR(50),
    "certificado_folio" VARCHAR(50),

    CONSTRAINT "pk_estudiante"
        PRIMARY KEY ("id_estudiante"),

    CONSTRAINT "uq_estudiante_sie"
        UNIQUE ("codigo_sie_cee"),

    CONSTRAINT "ck_estudiante_sie_no_vacio"
        CHECK (BTRIM("codigo_sie_cee") <> ''),

    CONSTRAINT "ck_estudiante_documento_no_vacio"
        CHECK (
            BTRIM("tipo_documento") <> ''
            AND BTRIM("numero_documento") <> ''
        ),

    CONSTRAINT "ck_estudiante_nombres_no_vacios"
        CHECK (
            BTRIM("apellido_paterno") <> ''
            AND BTRIM("nombre1") <> ''
            AND BTRIM("pais_nacimiento") <> ''
            AND BTRIM("departamento_nacimiento") <> ''
            AND BTRIM("provincia_nacimiento") <> ''
            AND BTRIM("localidad_nacimiento") <> ''
        ),

    CONSTRAINT "ck_estudiante_sexo_no_vacio"
        CHECK (BTRIM("sexo") <> ''),


    CONSTRAINT "ck_estudiante_complemento_no_vacio"
        CHECK (
            "complemento_documento" IS NULL
            OR BTRIM("complemento_documento") <> ''
        ),

    CONSTRAINT "ck_estudiante_certificado"
        CHECK (
            (
                "tiene_certificado_nacimiento" = FALSE
                AND "certificado_oficialia" IS NULL
                AND "certificado_libro" IS NULL
                AND "certificado_partida" IS NULL
                AND "certificado_folio" IS NULL
            )
            OR
            (
                "tiene_certificado_nacimiento" = TRUE
                AND "certificado_oficialia" IS NOT NULL
                AND BTRIM("certificado_oficialia") <> ''
                AND "certificado_libro" IS NOT NULL
                AND BTRIM("certificado_libro") <> ''
                AND "certificado_partida" IS NOT NULL
                AND BTRIM("certificado_partida") <> ''
                AND "certificado_folio" IS NOT NULL
                AND BTRIM("certificado_folio") <> ''
            )
        )
);

-- ============================================================
-- 2. DOMICILIO
-- Relación Estudiante 1:1 Domicilio
-- ============================================================
CREATE TABLE "Domicilio" (
    "id_domicilio" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "departamento" VARCHAR(100) NOT NULL,
    "provincia" VARCHAR(100) NOT NULL,
    "seccion_municipio" VARCHAR(100) NOT NULL,
    "localidad_comunidad" VARCHAR(100) NOT NULL,
    "zona_barrio_villa" VARCHAR(150) NOT NULL,
    "avenida_calle" VARCHAR(150) NOT NULL,
    "numero_vivienda" VARCHAR(30),
    "telefono" VARCHAR(30),
    "celular" VARCHAR(30),
    "direccion_procedencia_Centro_de_ Acogida_u_otro" VARCHAR(255),

    CONSTRAINT "pk_domicilio"
        PRIMARY KEY ("id_domicilio"),

    CONSTRAINT "uq_domicilio_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_domicilio_datos_no_vacios"
        CHECK (
            BTRIM("departamento") <> ''
            AND BTRIM("provincia") <> ''
            AND BTRIM("seccion_municipio") <> ''
            AND BTRIM("localidad_comunidad") <> ''
            AND BTRIM("zona_barrio_villa") <> ''
            AND BTRIM("avenida_calle") <> ''
        ),

    CONSTRAINT "fk_domicilio_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 3. IDIOMA
-- ============================================================
CREATE TABLE "Idioma" (
    "id_idioma" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "nombre_idioma" VARCHAR(100) NOT NULL,

    CONSTRAINT "ck_idioma_nombre_no_vacio"
        CHECK (BTRIM("nombre_idioma") <> ''),

    CONSTRAINT "pk_idioma"
        PRIMARY KEY ("id_idioma")
);

-- ============================================================
-- 4. IDIOMA Y CULTURA
-- Relación Estudiante N:M Idioma
-- ============================================================
CREATE TABLE "Idioma_y_Cultura" (
    "id_estudiante_idioma" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "id_idioma" BIGINT NOT NULL,
    "nacion_o_pueblo" VARCHAR(150),
    "idioma_aprendido_ninez" VARCHAR(100),

    CONSTRAINT "pk_idioma_cultura"
        PRIMARY KEY ("id_estudiante_idioma"),

    CONSTRAINT "uq_estudiante_idioma"
        UNIQUE ("id_estudiante", "id_idioma"),

    CONSTRAINT "fk_idioma_cultura_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT "ck_idioma_cultura_pueblo_no_vacio"
        CHECK (
            "nacion_o_pueblo" IS NULL
            OR BTRIM("nacion_o_pueblo") <> ''
        ),

    CONSTRAINT "fk_idioma_cultura_idioma"
        FOREIGN KEY ("id_idioma")
        REFERENCES "Idioma" ("id_idioma")
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- 5. GRUPO FAMILIAR
-- Datos generales del grupo familiar del estudiante
-- ============================================================
CREATE TABLE "Grupo_Familiar" (
    "id_familia" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "otra_institucion" VARCHAR(255),
    "otros_Familiares" BOOLEAN NOT NULL DEFAULT FALSE,
    "otros_No_Familiares" BOOLEAN NOT NULL DEFAULT FALSE,
    "familiar_con_ discapacidad" BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT "pk_grupo_familiar"
        PRIMARY KEY ("id_familia"),

    CONSTRAINT "uq_grupo_familiar_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_grupo_familiar_otra_institucion_no_vacia"
        CHECK (
            "otra_institucion" IS NULL
            OR BTRIM("otra_institucion") <> ''
        ),

    CONSTRAINT "fk_grupo_familiar_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 6. ESTUDIANTE FAMILIA / FAMILIAR
-- Una familia puede tener N integrantes.
-- ============================================================
CREATE TABLE "Estudiante_Familia" (
    "id_familiar" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_familia" BIGINT NOT NULL,
    "parentesco" VARCHAR(100) NOT NULL,

    CONSTRAINT "pk_estudiante_familia"
        PRIMARY KEY ("id_familiar"),

    CONSTRAINT "ck_familiar_parentesco_no_vacio"
        CHECK (BTRIM("parentesco") <> ''),

    CONSTRAINT "fk_estudiante_familia_familia"
        FOREIGN KEY ("id_familia")
        REFERENCES "Grupo_Familiar" ("id_familia")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 7. FAMILIAR CON DISCAPACIDAD
-- Solo contiene información específica de la discapacidad.
-- ============================================================
CREATE TABLE "familiar_discapacidad" (
    "id_familiar_discapacidad" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_familiar" BIGINT NOT NULL,
    "discapacidad" VARCHAR(150) NOT NULL,
    "parentesco" VARCHAR(100) NOT NULL,

    CONSTRAINT "pk_familiar_discapacidad"
        PRIMARY KEY ("id_familiar_discapacidad"),

    CONSTRAINT "uq_familiar_discapacidad"
        UNIQUE ("id_familiar"),

    CONSTRAINT "ck_familiar_discapacidad_no_vacia"
        CHECK (BTRIM("discapacidad") <> ''),

    CONSTRAINT "ck_familiar_discapacidad_parentesco_no_vacio"
        CHECK (BTRIM("parentesco") <> ''),

    CONSTRAINT "fk_familiar_discapacidad_familiar"
        FOREIGN KEY ("id_familiar")
        REFERENCES "Estudiante_Familia" ("id_familiar")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 8. SALUD DEL ESTUDIANTE
-- ============================================================
CREATE TABLE "Estudiante_salud" (
    "id_estudiante_salud" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "seguro_salud" BOOLEAN NOT NULL DEFAULT FALSE,
    "atencion_caja_seguro_de_salud" BOOLEAN NOT NULL DEFAULT FALSE,
    "atencion_salud_publica" BOOLEAN NOT NULL DEFAULT FALSE,
    "atencion_salud_privada" BOOLEAN NOT NULL DEFAULT FALSE,
    "atencion_vivienda" BOOLEAN NOT NULL DEFAULT FALSE,
    "atencion_medicina_tradicional" BOOLEAN NOT NULL DEFAULT FALSE,
    "atencion_automedicacion" BOOLEAN NOT NULL DEFAULT FALSE,
    "usa_medicacion_administrada_en_el_cee" BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT "pk_estudiante_salud"
        PRIMARY KEY ("id_estudiante_salud"),

    CONSTRAINT "uq_estudiante_salud"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "fk_estudiante_salud_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT "ck_salud_seguro_consistencia"
        CHECK (
            "seguro_salud" = TRUE
            OR "atencion_caja_seguro_de_salud" = FALSE
        )
);

-- ============================================================
-- 9. DISCAPACIDAD DEL ESTUDIANTE
-- ============================================================
CREATE TABLE "Discapacidad" (
    "id_discapacidad" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "numero_carnet_codepedis_o_ibc" VARCHAR(100),
    "tipo_discapacidad" VARCHAR(150) NOT NULL,
    "grado_discapacidad" VARCHAR(100) NOT NULL,
    "origen_discapacidad" VARCHAR(150) NOT NULL,

    CONSTRAINT "pk_discapacidad"
        PRIMARY KEY ("id_discapacidad"),

    CONSTRAINT "uq_discapacidad_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_discapacidad_datos_no_vacios"
        CHECK (
            BTRIM("tipo_discapacidad") <> ''
            AND BTRIM("grado_discapacidad") <> ''
            AND BTRIM("origen_discapacidad") <> ''
            AND (
                "numero_carnet_codepedis_o_ibc" IS NULL
                OR BTRIM("numero_carnet_codepedis_o_ibc") <> ''
            )
        ),

    CONSTRAINT "fk_discapacidad_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 10. TRASTORNO DEL ESPECTRO AUTISTA
-- ============================================================
CREATE TABLE "TEA" (
    "id_tea" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "tiene_TEA" BOOLEAN NOT NULL DEFAULT FALSE,
    "tipo_tea" VARCHAR(150) NOT NULL,

    CONSTRAINT "pk_tea"
        PRIMARY KEY ("id_tea"),

    CONSTRAINT "uq_tea_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_tea_tipo_no_vacio"
        CHECK (BTRIM("tipo_tea") <> ''),

    CONSTRAINT "ck_tea_debe_ser_true_si_existe"
        CHECK ("tiene_TEA" = TRUE),

    CONSTRAINT "fk_tea_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 11. DIFICULTAD DE APRENDIZAJE
-- ============================================================
CREATE TABLE "DIFICULTAD_APRENDIZAJE" (
    "id_dificultad_aprendizaje" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "tiene_diagnostico" BOOLEAN NOT NULL DEFAULT FALSE,
    "tiene_informe_pedagogico" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_directa" BOOLEAN NOT NULL DEFAULT FALSE,
    "area_lectura_escritura" BOOLEAN NOT NULL DEFAULT FALSE,
    "area_razonamiento_verbal_logico" BOOLEAN NOT NULL DEFAULT FALSE,
    "area_calculo_matematico" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_indirecta" BOOLEAN NOT NULL DEFAULT FALSE,
    "apoyo_tecnico_pedagogico" BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT "pk_dificultad_aprendizaje"
        PRIMARY KEY ("id_dificultad_aprendizaje"),

    CONSTRAINT "uq_dificultad_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_dificultad_debe_tener_diagnostico_si_existe"
        CHECK ("tiene_diagnostico" = TRUE),

    CONSTRAINT "ck_dificultad_al_menos_un_dato"
        CHECK (
            "tiene_diagnostico"
            OR "tiene_informe_pedagogico"
            OR "modalidad_directa"
            OR "area_lectura_escritura"
            OR "area_razonamiento_verbal_logico"
            OR "area_calculo_matematico"
            OR "modalidad_indirecta"
            OR "apoyo_tecnico_pedagogico"
        ),

    CONSTRAINT "fk_dificultad_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 12. TALENTO EXTRAORDINARIO
-- ============================================================
CREATE TABLE "TALENTO_EXTRAORDINARIO" (
    "id_talento" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "talento_extraordinario" BOOLEAN NOT NULL DEFAULT FALSE,
    "tipo_talento" VARCHAR(150) NOT NULL,
    "coeficiente_intelectual" INTEGER,
    "talento_artistico" BOOLEAN NOT NULL DEFAULT FALSE,
    "talento_humanistico" BOOLEAN NOT NULL DEFAULT FALSE,
    "talento_musical" BOOLEAN NOT NULL DEFAULT FALSE,
    "talento_deportivo" BOOLEAN NOT NULL DEFAULT FALSE,
    "talento_cientifico_tecnologico" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_directa" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_directa_tutorias" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_directa_acciones_complementarias" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_directa_escuelas_mentoras" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_directa_practicas_voluntariado" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_indirecta" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_indirecta_orientacion_precoz" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_indirecta_adaptaciones_curriculares" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_indirecta_aceleracion_educativa" BOOLEAN NOT NULL DEFAULT FALSE,
    "modalidad_indirecta_otros" BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT "pk_talento"
        PRIMARY KEY ("id_talento"),

    CONSTRAINT "uq_talento_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_talento_tipo_no_vacio"
        CHECK (BTRIM("tipo_talento") <> ''),

    CONSTRAINT "ck_talento_debe_ser_true_si_existe"
        CHECK ("talento_extraordinario" = TRUE),

    CONSTRAINT "ck_talento_modalidad_directa_consistencia"
        CHECK (
            "modalidad_directa" = TRUE
            OR (
                "modalidad_directa_tutorias" = FALSE
                AND "modalidad_directa_acciones_complementarias" = FALSE
                AND "modalidad_directa_escuelas_mentoras" = FALSE
                AND "modalidad_directa_practicas_voluntariado" = FALSE
            )
        ),

    CONSTRAINT "ck_talento_modalidad_indirecta_consistencia"
        CHECK (
            "modalidad_indirecta" = TRUE
            OR (
                "modalidad_indirecta_orientacion_precoz" = FALSE
                AND "modalidad_indirecta_adaptaciones_curriculares" = FALSE
                AND "modalidad_indirecta_aceleracion_educativa" = FALSE
                AND "modalidad_indirecta_otros" = FALSE
            )
        ),

    CONSTRAINT "fk_talento_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT "ck_coeficiente_intelectual"
        CHECK (
            "coeficiente_intelectual" IS NULL
            OR "coeficiente_intelectual" > 0
        )
);

-- ============================================================
-- 13. ACCESO A SERVICIOS BÁSICOS
-- ============================================================
CREATE TABLE "ACCESO_SERVICIOS_BASICOS" (
    "id_acceso_servicios" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "acceso_agua_canieria" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_bano" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_alcantarillado" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_energia_electrica" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_recojo_basura" BOOLEAN NOT NULL DEFAULT FALSE,
    "servicios_accesibles_adaptados" VARCHAR(255),

    CONSTRAINT "pk_acceso_servicios"
        PRIMARY KEY ("id_acceso_servicios"),

    CONSTRAINT "uq_acceso_servicios_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_acceso_servicios_otro_no_vacio"
        CHECK (
            "servicios_accesibles_adaptados" IS NULL
            OR BTRIM("servicios_accesibles_adaptados") <> ''
        ),

    CONSTRAINT "fk_acceso_servicios_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 14. TECNOLOGÍA Y COMUNICACIÓN
-- ============================================================
CREATE TABLE "TECNOLOGIA_COMUNICACION" (
    "id_tecnologia" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "acceso_radio" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_televisor" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_telefono" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_celular" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_computadora" BOOLEAN NOT NULL DEFAULT FALSE,
    "usa_estos_medios_o_son_accesibles" VARCHAR(255),

    CONSTRAINT "pk_tecnologia"
        PRIMARY KEY ("id_tecnologia"),

    CONSTRAINT "uq_tecnologia_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_tecnologia_otro_no_vacio"
        CHECK (
            "usa_estos_medios_o_son_accesibles" IS NULL
            OR BTRIM("usa_estos_medios_o_son_accesibles") <> ''
        ),

    CONSTRAINT "fk_tecnologia_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 15. ACCESO A INTERNET
-- ============================================================
CREATE TABLE "ACCESO_INTERNET" (
    "id_acceso_internet" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "acceso_vivienda" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_lugares_publicos" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_cee" BOOLEAN NOT NULL DEFAULT FALSE,
    "acceso_telefono_celular" BOOLEAN NOT NULL DEFAULT FALSE,
    "no_accede_internet" BOOLEAN NOT NULL DEFAULT FALSE,
    "frecuencia_uso" VARCHAR(100),

    CONSTRAINT "pk_acceso_internet"
        PRIMARY KEY ("id_acceso_internet"),

    CONSTRAINT "uq_acceso_internet_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_acceso_internet_frecuencia_no_vacia"
        CHECK (
            "frecuencia_uso" IS NULL
            OR BTRIM("frecuencia_uso") <> ''
        ),

    CONSTRAINT "fk_acceso_internet_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT "ck_no_accede_internet_consistencia"
        CHECK (
            (
                "no_accede_internet" = TRUE
                AND "acceso_vivienda" = FALSE
                AND "acceso_lugares_publicos" = FALSE
                AND "acceso_cee" = FALSE
                AND "acceso_telefono_celular" = FALSE
            )
            OR
            (
                "no_accede_internet" = FALSE
                AND (
                    "acceso_vivienda" = TRUE
                    OR "acceso_lugares_publicos" = TRUE
                    OR "acceso_cee" = TRUE
                    OR "acceso_telefono_celular" = TRUE
                )
            )
        )
);

-- ============================================================
-- 16. INSCRIPCIÓN
-- Una inscripción vigente por estudiante.
-- Si se requiere histórico, añadir gestion/periodo.
-- ============================================================
CREATE TABLE "Inscripcion" (
    "id_inscripcion" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "paralelo" VARCHAR(30),
    "programa_no_escolarizado" BOOLEAN NOT NULL DEFAULT FALSE,
    "nivel_inicial" VARCHAR(100),
    "nivel_primaria" VARCHAR(100),
    "programa_auditiva" VARCHAR(150),
    "atencion_temprana" BOOLEAN NOT NULL DEFAULT FALSE,
    "independencia_personal" VARCHAR(150),
    "independencia_social" VARCHAR(150),
    "programa_intelectual" VARCHAR(150),
    "programas_visual_fisica_motora_mental" VARCHAR(255),
    "formacion_tecnica_productiva" VARCHAR(255),
    "especificacion" VARCHAR(255),

    CONSTRAINT "pk_inscripcion"
        PRIMARY KEY ("id_inscripcion"),

    CONSTRAINT "uq_inscripcion_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_inscripcion_textos_no_vacios"
        CHECK (
            ("paralelo" IS NULL OR BTRIM("paralelo") <> '')
            AND ("nivel_inicial" IS NULL OR BTRIM("nivel_inicial") <> '')
            AND ("nivel_primaria" IS NULL OR BTRIM("nivel_primaria") <> '')
            AND ("programa_auditiva" IS NULL OR BTRIM("programa_auditiva") <> '')
            AND ("independencia_personal" IS NULL OR BTRIM("independencia_personal") <> '')
            AND ("independencia_social" IS NULL OR BTRIM("independencia_social") <> '')
            AND ("programa_intelectual" IS NULL OR BTRIM("programa_intelectual") <> '')
            AND ("programas_visual_fisica_motora_mental" IS NULL OR BTRIM("programas_visual_fisica_motora_mental") <> '')
            AND ("formacion_tecnica_productiva" IS NULL OR BTRIM("formacion_tecnica_productiva") <> '')
            AND ("especificacion" IS NULL OR BTRIM("especificacion") <> '')
        ),

    CONSTRAINT "fk_inscripcion_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 17. MODALIDAD INDIRECTA
-- ============================================================
CREATE TABLE "Modalidad_indirecta" (
    "id_modalidad_indirecta" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "estudiante_discapacidad" BOOLEAN NOT NULL DEFAULT FALSE,
    "estudiante_dificultad_aprendizaje" BOOLEAN NOT NULL DEFAULT FALSE,
    "estudiante_talento_extraordinario" BOOLEAN NOT NULL DEFAULT FALSE,
    "area_nivel" VARCHAR(150),
    "grado" VARCHAR(100),
    "nombre_institucion" VARCHAR(255),

    CONSTRAINT "ck_modalidad_indirecta_tipo"
        CHECK (
            "estudiante_discapacidad"
            OR "estudiante_dificultad_aprendizaje"
            OR "estudiante_talento_extraordinario"
        ),

    CONSTRAINT "pk_modalidad_indirecta"
        PRIMARY KEY ("id_modalidad_indirecta"),

    CONSTRAINT "uq_modalidad_indirecta_estudiante"
        UNIQUE ("id_estudiante"),

    CONSTRAINT "ck_modalidad_indirecta_textos_no_vacios"
        CHECK (
            ("area_nivel" IS NULL OR BTRIM("area_nivel") <> '')
            AND ("grado" IS NULL OR BTRIM("grado") <> '')
            AND ("nombre_institucion" IS NULL OR BTRIM("nombre_institucion") <> '')
        ),

    CONSTRAINT "fk_modalidad_indirecta_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 18. SERVICIO MULTIDISCIPLINARIO
-- ============================================================
CREATE TABLE "Servicio_Multidisciplinario" (
    "id_servicio" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "nombre_servicio" VARCHAR(150) NOT NULL,

    CONSTRAINT "ck_servicio_nombre_no_vacio"
        CHECK (BTRIM("nombre_servicio") <> ''),

    CONSTRAINT "pk_servicio"
        PRIMARY KEY ("id_servicio")
);

-- ============================================================
-- 19. ESTUDIANTE SERVICIO
-- Relación N:M entre estudiante y servicio.
-- ============================================================
CREATE TABLE "Estudiante_Servicio" (
    "id_estudiante_servicio" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "id_servicio" BIGINT NOT NULL,
    "especificar_otro" VARCHAR(255),

    CONSTRAINT "pk_estudiante_servicio"
        PRIMARY KEY ("id_estudiante_servicio"),

    CONSTRAINT "uq_estudiante_servicio"
        UNIQUE ("id_estudiante", "id_servicio"),

    CONSTRAINT "fk_estudiante_servicio_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT "ck_estudiante_servicio_otro_no_vacio"
        CHECK (
            "especificar_otro" IS NULL
            OR BTRIM("especificar_otro") <> ''
        ),

    CONSTRAINT "fk_estudiante_servicio_servicio"
        FOREIGN KEY ("id_servicio")
        REFERENCES "Servicio_Multidisciplinario" ("id_servicio")
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- 20. PADRE / MADRE / TUTOR
-- ============================================================
CREATE TABLE "Padre_Madre_Tutor" (
    "id_padre_madre_tutor" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "complemento" VARCHAR(20),
    "expedido" VARCHAR(100),
    "apellido_paterno" VARCHAR(100) NOT NULL,
    "apellido_materno" VARCHAR(100),
    "nombre" VARCHAR(150) NOT NULL,
    "fecha_nacimiento" DATE,
    "idioma_frecuente" VARCHAR(100),
    "ocupacion_laboral" VARCHAR(150),
    "grado_instruccion" VARCHAR(150),
    "parentesco" VARCHAR(100) NOT NULL,
    "tipo_convivencia" VARCHAR(100),

    CONSTRAINT "pk_padre_madre_tutor"
        PRIMARY KEY ("id_padre_madre_tutor"),

    CONSTRAINT "ck_tutor_datos_no_vacios"
        CHECK (
            BTRIM("apellido_paterno") <> ''
            AND BTRIM("nombre") <> ''
            AND BTRIM("parentesco") <> ''
        ),

    CONSTRAINT "ck_tutor_complemento_no_vacio"
        CHECK (
            "complemento" IS NULL
            OR BTRIM("complemento") <> ''
        )
);

-- ============================================================
-- 21. ESTUDIANTE TUTOR
-- Relación N:M entre estudiante y padre/madre/tutor.
-- ============================================================
CREATE TABLE "Estudiante_Tutor" (
    "id_estudiante_tutor" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "id_estudiante" BIGINT NOT NULL,
    "id_padre_madre_tutor" BIGINT NOT NULL,

    CONSTRAINT "pk_estudiante_tutor"
        PRIMARY KEY ("id_estudiante_tutor"),

    CONSTRAINT "uq_estudiante_tutor"
        UNIQUE ("id_estudiante", "id_padre_madre_tutor"),

    CONSTRAINT "fk_estudiante_tutor_estudiante"
        FOREIGN KEY ("id_estudiante")
        REFERENCES "Estudiante" ("id_estudiante")
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT "fk_estudiante_tutor_padre"
        FOREIGN KEY ("id_padre_madre_tutor")
        REFERENCES "Padre_Madre_Tutor" ("id_padre_madre_tutor")
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- ÍNDICES PARA FK
-- ============================================================
CREATE INDEX "idx_idioma_cultura_estudiante"
    ON "Idioma_y_Cultura" ("id_estudiante");

CREATE INDEX "idx_idioma_cultura_idioma"
    ON "Idioma_y_Cultura" ("id_idioma");

CREATE INDEX "idx_familiar_familia"
    ON "Estudiante_Familia" ("id_familia");

CREATE INDEX "idx_modalidad_indirecta_estudiante"
    ON "Modalidad_indirecta" ("id_estudiante");

-- ============================================================
-- REGLAS DE INTEGRIDAD ADICIONALES
-- ============================================================

-- PostgreSQL no debe usar CURRENT_DATE directamente en CHECK:
-- la fecha actual cambia con el tiempo y el CHECK se evalúa al
-- insertar/actualizar, no de forma continua. Se valida mediante trigger.

CREATE OR REPLACE FUNCTION "fn_validar_fecha_nacimiento_no_futura"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW."fecha_nacimiento" IS NOT NULL
       AND NEW."fecha_nacimiento" > CURRENT_DATE THEN
        RAISE EXCEPTION
            'La fecha de nacimiento no puede ser futura: %',
            NEW."fecha_nacimiento";
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_estudiante_fecha_nacimiento"
BEFORE INSERT OR UPDATE OF "fecha_nacimiento"
ON "Estudiante"
FOR EACH ROW
EXECUTE FUNCTION "fn_validar_fecha_nacimiento_no_futura"();

CREATE TRIGGER "trg_tutor_fecha_nacimiento"
BEFORE INSERT OR UPDATE OF "fecha_nacimiento"
ON "Padre_Madre_Tutor"
FOR EACH ROW
EXECUTE FUNCTION "fn_validar_fecha_nacimiento_no_futura"();

-- Un documento con complemento NULL no debe poder repetirse.
-- Se usan índices parciales para que la regla sea compatible con
-- versiones de PostgreSQL anteriores a 15.
CREATE UNIQUE INDEX "uq_estudiante_documento_sin_complemento"
    ON "Estudiante" ("tipo_documento", "numero_documento")
    WHERE "complemento_documento" IS NULL;

CREATE UNIQUE INDEX "uq_estudiante_documento_con_complemento"
    ON "Estudiante" ("tipo_documento", "numero_documento", "complemento_documento")
    WHERE "complemento_documento" IS NOT NULL;

-- Evita duplicados por diferencias de mayúsculas/minúsculas en catálogos.
CREATE UNIQUE INDEX "uq_idioma_nombre_ci"
    ON "Idioma" (LOWER(BTRIM("nombre_idioma")));

CREATE UNIQUE INDEX "uq_servicio_nombre_ci"
    ON "Servicio_Multidisciplinario" (LOWER(BTRIM("nombre_servicio")));

-- "Otro" debe tener una especificación; los demás servicios no deben
-- guardar texto en especificar_otro.
CREATE OR REPLACE FUNCTION "fn_validar_especificar_otro_servicio"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_nombre_servicio VARCHAR(150);
BEGIN
    SELECT "nombre_servicio"
      INTO v_nombre_servicio
      FROM "Servicio_Multidisciplinario"
     WHERE "id_servicio" = NEW."id_servicio";

    IF v_nombre_servicio IS NULL THEN
        RAISE EXCEPTION
            'El servicio % no existe.',
            NEW."id_servicio";
    END IF;

    IF LOWER(BTRIM(v_nombre_servicio)) = 'otro' THEN
        IF NULLIF(BTRIM(NEW."especificar_otro"), '') IS NULL THEN
            RAISE EXCEPTION
                'Debe especificar el servicio cuando se selecciona "Otro".';
        END IF;
    ELSE
        IF NULLIF(BTRIM(NEW."especificar_otro"), '') IS NOT NULL THEN
            RAISE EXCEPTION
                'especificar_otro solo puede utilizarse con el servicio "Otro".';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_estudiante_servicio_otro"
BEFORE INSERT OR UPDATE OF "id_servicio", "especificar_otro"
ON "Estudiante_Servicio"
FOR EACH ROW
EXECUTE FUNCTION "fn_validar_especificar_otro_servicio"();

-- ============================================================
-- ÍNDICES / INTEGRIDAD ADICIONAL
-- ============================================================

-- Evita duplicados por espacios o diferencias de mayúsculas en el código SIE.
CREATE UNIQUE INDEX "uq_estudiante_sie_normalizado"
    ON "Estudiante" (LOWER(BTRIM("codigo_sie_cee")));

-- Evita que los datos de teléfono/celular consistan solo en espacios.
ALTER TABLE "Domicilio"
    ADD CONSTRAINT "ck_domicilio_telefonos_no_vacios"
    CHECK (
        ("telefono" IS NULL OR BTRIM("telefono") <> '')
        AND ("celular" IS NULL OR BTRIM("celular") <> '')
    );

-- Si existe información de frecuencia, debe existir algún medio de acceso.
ALTER TABLE "ACCESO_INTERNET"
    ADD CONSTRAINT "ck_internet_frecuencia_con_acceso"
    CHECK (
        "frecuencia_uso" IS NULL
        OR "no_accede_internet" = FALSE
    );

-- Si se marca una modalidad específica, la modalidad general debe estar marcada.
ALTER TABLE "TALENTO_EXTRAORDINARIO"
    ADD CONSTRAINT "ck_talento_modalidades_generales"
    CHECK (
        (
            "modalidad_directa_tutorias"
            OR "modalidad_directa_acciones_complementarias"
            OR "modalidad_directa_escuelas_mentoras"
            OR "modalidad_directa_practicas_voluntariado"
        ) = FALSE
        OR "modalidad_directa" = TRUE
    );

ALTER TABLE "TALENTO_EXTRAORDINARIO"
    ADD CONSTRAINT "ck_talento_modalidad_indirecta_general"
    CHECK (
        (
            "modalidad_indirecta_orientacion_precoz"
            OR "modalidad_indirecta_adaptaciones_curriculares"
            OR "modalidad_indirecta_aceleracion_educativa"
            OR "modalidad_indirecta_otros"
        ) = FALSE
        OR "modalidad_indirecta" = TRUE
    );

-- ============================================================
-- DATOS INICIALES
-- ============================================================
INSERT INTO "Servicio_Multidisciplinario" ("nombre_servicio")
VALUES
    ('Psicopedagogia'),
    ('Psicologia'),
    ('Fisioterapia'),
    ('Fonoaudiologia'),
    ('Psicomotricidad'),
    ('Terapia Ocupacional'),
    ('Oftalmologia'),
    ('Neurologia'),
    ('Trabajo Social'),
    ('Otro')
ON CONFLICT DO NOTHING;

INSERT INTO "Idioma" ("nombre_idioma")
VALUES
    ('Castellano'),
    ('Quechua'),
    ('Aymara'),
    ('Guaraní'),
    ('Otro')
ON CONFLICT DO NOTHING;

-- ============================================================
-- REGLAS PARA BANDERAS DE PRESENCIA DE INFORMACION OPCIONAL
-- ============================================================

-- Si familiar_con_ discapacidad = FALSE, no se permite registrar
-- familiares en familiar_discapacidad. Si es TRUE, debe existir al
-- menos un registro al finalizar la transaccion.
CREATE OR REPLACE FUNCTION "fn_validar_familiar_discapacidad_insert"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_tiene BOOLEAN;
BEGIN
    -- El trigger se dispara sobre familiar_discapacidad, cuyo registro NO
    -- tiene "id_familia"; se resuelve a traves de Estudiante_Familia.
    SELECT gf."familiar_con_ discapacidad"
      INTO v_tiene
      FROM "Estudiante_Familia" ef
      JOIN "Grupo_Familiar" gf
        ON gf."id_familia" = ef."id_familia"
     WHERE ef."id_familiar" = NEW."id_familiar";

    IF NOT FOUND OR v_tiene IS NULL THEN
        RAISE EXCEPTION 'La familia del familiar % no existe.', NEW."id_familiar";
    END IF;

    IF v_tiene = FALSE THEN
        RAISE EXCEPTION 'No se puede llenar familiar_discapacidad cuando familiar_con_ discapacidad = FALSE.';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_familiar_discapacidad_bandera"
BEFORE INSERT OR UPDATE OF "id_familiar"
ON "familiar_discapacidad"
FOR EACH ROW
EXECUTE FUNCTION "fn_validar_familiar_discapacidad_insert"();

CREATE OR REPLACE FUNCTION "fn_validar_grupo_familiar_discapacidad_final"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_familia BIGINT;
    v_id_familiar BIGINT;
    v_tiene BOOLEAN;
    v_cantidad BIGINT;
BEGIN
    -- La funcion se comparte entre dos tablas con columnas distintas:
    --   * Grupo_Familiar       -> el registro SI tiene "id_familia"
    --   * familiar_discapacidad-> NO tiene "id_familia"; se resuelve via Estudiante_Familia
    IF TG_TABLE_NAME = 'familiar_discapacidad' THEN
        IF TG_OP = 'DELETE' THEN
            v_id_familiar := OLD."id_familiar";
        ELSE
            v_id_familiar := NEW."id_familiar";
        END IF;

        SELECT ef."id_familia"
          INTO v_id_familia
          FROM "Estudiante_Familia" ef
         WHERE ef."id_familiar" = v_id_familiar;
    ELSE
        v_id_familia := COALESCE(NEW."id_familia", OLD."id_familia");
    END IF;

    -- Si el familiar o la familia ya fueron eliminados (borrado en cascada),
    -- no hay nada que validar.
    IF v_id_familia IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT "familiar_con_ discapacidad"
      INTO v_tiene
      FROM "Grupo_Familiar"
     WHERE "id_familia" = v_id_familia;

    IF v_tiene IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT COUNT(*)
      INTO v_cantidad
      FROM "familiar_discapacidad" fd
      JOIN "Estudiante_Familia" ef
        ON ef."id_familiar" = fd."id_familiar"
     WHERE ef."id_familia" = v_id_familia;

    IF v_tiene = TRUE AND v_cantidad = 0 THEN
        RAISE EXCEPTION 'La familia % indica familiar con discapacidad, pero no existe registro en familiar_discapacidad.', v_id_familia;
    ELSIF v_tiene = FALSE AND v_cantidad > 0 THEN
        RAISE EXCEPTION 'La familia % no indica familiar con discapacidad, pero existen registros en familiar_discapacidad.', v_id_familia;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER "trg_grupo_familiar_discapacidad_final"
AFTER INSERT OR UPDATE OF "familiar_con_ discapacidad"
ON "Grupo_Familiar"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION "fn_validar_grupo_familiar_discapacidad_final"();

CREATE CONSTRAINT TRIGGER "trg_familiar_discapacidad_final"
AFTER INSERT OR UPDATE OR DELETE
ON "familiar_discapacidad"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION "fn_validar_grupo_familiar_discapacidad_final"();

-- Las tablas TEA, DIFICULTAD_APRENDIZAJE y TALENTO_EXTRAORDINARIO
-- solo se deben poblar cuando su respectiva bandera sea TRUE.
-- Los CHECK de cada tabla impiden registrar una fila con FALSE.

-- ============================================================
-- VALIDACION DE DATOS OPCIONALES DE DOMICILIO
-- ============================================================
ALTER TABLE "Domicilio"
    ADD CONSTRAINT "ck_domicilio_direccion_procedencia_no_vacia"
    CHECK (
        "direccion_procedencia_Centro_de_ Acogida_u_otro" IS NULL
        OR BTRIM("direccion_procedencia_Centro_de_ Acogida_u_otro") <> ''
    );


COMMIT;

-- ============================================================
-- VERIFICACIONES ADICIONALES DE LA VERSION CORREGIDA
-- ============================================================
-- 1) La BDD conserva exactamente 21 tablas.
-- 2) Las relaciones 1:1 usan UNIQUE sobre la FK correspondiente.
-- 3) Las relaciones N:M usan UNIQUE compuesto.
-- 4) Las reglas que dependen de CURRENT_DATE usan TRIGGER.
-- 5) Los catálogos tienen unicidad funcional por nombre normalizado.
-- 6) No se conserva información redundante de discapacidad familiar.
-- 7) ACCESO_INTERNET impide combinaciones contradictorias.
-- 8) Modalidad_indirecta exige al menos un tipo.
-- 9) Estudiante_Servicio valida correctamente el caso "Otro".
-- 10) Los campos obligatorios de identidad y tutor/familiar no aceptan
--     cadenas vacías.
-- 11) La atención por caja/seguro no puede marcarse si seguro_salud = FALSE.
-- 12) Los textos opcionales no aceptan cadenas vacías.
-- 13) Se evita duplicar el código SIE por diferencias de mayúsculas/espacios.
-- 14) Las modalidades de talento mantienen consistencia entre opción general y detalle.
-- 15) Las tablas 1:1 mantienen UNIQUE sobre su FK; las N:M mantienen UNIQUE compuesto.
--
-- ============================================================
-- FIN DE LA BDD DEFINITIVA
-- ============================================================
